# Generated by Django 2.0.3 on 2019-06-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=64)),
                ('small', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('large', models.DecimalField(decimal_places=2, max_digits=8)),
                ('isdinnerplatter', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PizzaAndSubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=64)),
                ('small', models.DecimalField(decimal_places=2, max_digits=8)),
                ('large', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ispizza', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ToppingsAndExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('isextra', models.BooleanField()),
            ],
        ),
    ]
