# Generated by Django 2.0.3 on 2019-06-18 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='toppingorextra',
        ),
    ]
