# Generated by Django 2.0.3 on 2019-06-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_orders_toppingorextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
